import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, '../../data');
const UPLOADED_COOKIES = path.join(DATA_DIR, 'cookies.txt');
const AUTH_CONFIG = path.join(DATA_DIR, 'media-auth.json');

const BROWSERS = ['chrome', 'chromium', 'firefox', 'brave', 'edge', 'opera', 'vivaldi', 'safari'];

const DEFAULT_AUTH = {
  method: 'none',
  browser: 'chrome',
  browserProfile: '',
  instagram: { sessionid: '', ds_user_id: '', csrftoken: '' },
  facebook: { c_user: '', xs: '' },
  credentials: { username: '', passwordEnc: '' },
};

function ensureDataDir() {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

function encryptSecret(text) {
  if (!text) return '';
  const secret = process.env.JWT_SECRET || 'rdm-default-key';
  const key = crypto.scryptSync(secret, 'rdm-auth', 32);
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const enc = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return `${iv.toString('hex')}:${tag.toString('hex')}:${enc.toString('hex')}`;
}

function decryptSecret(payload) {
  if (!payload) return '';
  const secret = process.env.JWT_SECRET || 'rdm-default-key';
  const key = crypto.scryptSync(secret, 'rdm-auth', 32);
  const [ivHex, tagHex, dataHex] = payload.split(':');
  const decipher = crypto.createDecipheriv(
    'aes-256-gcm',
    key,
    Buffer.from(ivHex, 'hex'),
  );
  decipher.setAuthTag(Buffer.from(tagHex, 'hex'));
  return Buffer.concat([
    decipher.update(Buffer.from(dataHex, 'hex')),
    decipher.final(),
  ]).toString('utf8');
}

export function loadAuthConfig() {
  try {
    const raw = fs.readFileSync(AUTH_CONFIG, 'utf8');
    return { ...DEFAULT_AUTH, ...JSON.parse(raw) };
  } catch {
    return { ...DEFAULT_AUTH };
  }
}

function saveAuthConfig(config) {
  ensureDataDir();
  fs.writeFileSync(AUTH_CONFIG, JSON.stringify(config, null, 2), { mode: 0o600 });
}

function netscapeLine(domain, name, value, expiry) {
  return `${domain}\tTRUE\t/\tTRUE\t${expiry}\t${name}\t${value}`;
}

export function buildNetscapeFromSession({ instagram = {}, facebook = {} }) {
  const expiry = Math.floor(Date.now() / 1000) + 365 * 24 * 3600;
  const lines = ['# Netscape HTTP Cookie File', '# Generated by RDM'];

  const add = (domain, name, value) => {
    if (value?.trim()) lines.push(netscapeLine(domain, name, value.trim(), expiry));
  };

  add('.instagram.com', 'sessionid', instagram.sessionid);
  add('.instagram.com', 'ds_user_id', instagram.ds_user_id);
  add('.instagram.com', 'csrftoken', instagram.csrftoken);
  add('.facebook.com', 'c_user', facebook.c_user);
  add('.facebook.com', 'xs', facebook.xs);

  if (lines.length <= 2) {
    throw new Error('Provide at least one Instagram or Facebook session value');
  }

  return `${lines.join('\n')}\n`;
}

function writeSessionCookies(config) {
  const content = buildNetscapeFromSession(config);
  fs.writeFileSync(UPLOADED_COOKIES, content, { mode: 0o600 });
}

function analyzeCookiesFile(cookiesPath) {
  let content = '';
  let updatedAt = null;
  try {
    const stat = fs.statSync(cookiesPath);
    updatedAt = stat.mtime.toISOString();
    content = fs.readFileSync(cookiesPath, 'utf8');
  } catch {
    return { hasInstagram: false, hasFacebook: false, domains: [], updatedAt: null };
  }

  const domains = new Set();
  for (const line of content.split('\n')) {
    if (!line || line.startsWith('#')) continue;
    const parts = line.split('\t');
    if (parts.length >= 1) domains.add(parts[0].trim().toLowerCase());
  }
  const domainList = [...domains];
  const hasAgeGateSite = domainList.some((d) =>
    /pornhub|xvideos|xhamster|redtube|youporn|spankbang|xnxx|eporner/.test(d),
  );
  return {
    hasInstagram: domainList.some((d) => d.includes('instagram.com')),
    hasFacebook: domainList.some((d) => d.includes('facebook.com')),
    hasAgeGateSite,
    domains: domainList.slice(0, 20),
    domainCount: domainList.length,
    updatedAt,
  };
}

/** Cookie header string for Instagram API requests (session tokens + cookies.txt). */
export function getInstagramCookieHeader() {
  const parts = [];
  const config = loadAuthConfig();

  if (config.instagram?.sessionid?.trim()) {
    parts.push(`sessionid=${config.instagram.sessionid.trim()}`);
  }
  if (config.instagram?.ds_user_id?.trim()) {
    parts.push(`ds_user_id=${config.instagram.ds_user_id.trim()}`);
  }
  if (config.instagram?.csrftoken?.trim()) {
    parts.push(`csrftoken=${config.instagram.csrftoken.trim()}`);
  }

  const paths = [
    process.env.YTDLP_COOKIES_FILE?.trim(),
    fs.existsSync(UPLOADED_COOKIES) ? UPLOADED_COOKIES : null,
  ].filter(Boolean);

  for (const cookiesPath of paths) {
    try {
      if (!cookiesPath || !fs.existsSync(cookiesPath)) continue;
      for (const line of fs.readFileSync(cookiesPath, 'utf8').split('\n')) {
        if (!line || line.startsWith('#')) continue;
        const cols = line.split('\t');
        if (cols.length < 7) continue;
        const domain = cols[0].toLowerCase();
        if (!domain.includes('instagram.com')) continue;
        const name = cols[5];
        const value = cols[6];
        if (name && value && !parts.some((p) => p.startsWith(`${name}=`))) {
          parts.push(`${name}=${value}`);
        }
      }
    } catch {
      /* ignore */
    }
  }

  return parts.length ? parts.join('; ') : '';
}

function hasInstagramSessionFields(config = loadAuthConfig()) {
  return Boolean(
    config.instagram?.sessionid?.trim() ||
      config.instagram?.ds_user_id?.trim() ||
      config.instagram?.csrftoken?.trim(),
  );
}

function cookiesFileHasInstagram(cookiesPath = UPLOADED_COOKIES) {
  try {
    if (!cookiesPath || !fs.existsSync(cookiesPath)) return false;
    return fs.readFileSync(cookiesPath, 'utf8').toLowerCase().includes('instagram.com');
  } catch {
    return false;
  }
}

/** Write Instagram session tokens to cookies.txt for yt-dlp (Instagram-only, no Facebook). */
export function ensureInstagramCookieFile(config = loadAuthConfig()) {
  if (!hasInstagramSessionFields(config)) return false;
  try {
    writeSessionCookies({ instagram: config.instagram, facebook: {} });
    return fs.existsSync(UPLOADED_COOKIES);
  } catch {
    return false;
  }
}

/** yt-dlp CLI args for authentication */
export function getYtdlpAuthArgs() {
  return getYtdlpAuthArgsForUrl(null);
}

/** yt-dlp auth — Instagram always uses cookies when configured (required since ~2024). */
export function getYtdlpAuthArgsForUrl(url = null) {
  const publicOnly = process.env.PUBLIC_MEDIA_ONLY !== 'false';

  const envPath = process.env.YTDLP_COOKIES_FILE?.trim();
  if (envPath && fs.existsSync(envPath)) {
    return { args: ['--cookies', envPath], method: 'env' };
  }

  const config = loadAuthConfig();
  let isInstagram = false;
  if (url) {
    try {
      isInstagram = /instagram\.com/i.test(new URL(String(url)).hostname);
    } catch {
      isInstagram = false;
    }
  }

  switch (config.method) {
    case 'browser': {
      const browser = BROWSERS.includes(config.browser) ? config.browser : 'chrome';
      const spec = config.browserProfile?.trim()
        ? `${browser}:${config.browserProfile.trim()}`
        : browser;
      return { args: ['--cookies-from-browser', spec], method: 'browser', browser: spec };
    }
    case 'upload': {
      if (fs.existsSync(UPLOADED_COOKIES)) {
        return { args: ['--cookies', UPLOADED_COOKIES], method: 'upload' };
      }
      return { args: [], method: 'upload' };
    }
    case 'session': {
      if (isInstagram && hasInstagramSessionFields(config)) {
        ensureInstagramCookieFile(config);
        if (fs.existsSync(UPLOADED_COOKIES)) {
          return { args: ['--cookies', UPLOADED_COOKIES], method: 'session-instagram' };
        }
      }
      if (publicOnly) {
        return { args: [], method: 'public' };
      }
      writeSessionCookies(config);
      return { args: ['--cookies', UPLOADED_COOKIES], method: 'session' };
    }
    case 'credentials': {
      if (publicOnly && !isInstagram) {
        return { args: [], method: 'public' };
      }
      const password = decryptSecret(config.credentials?.passwordEnc);
      const username = config.credentials?.username?.trim();
      if (username && password) {
        return {
          args: ['--username', username, '--password', password],
          method: 'credentials',
          username,
        };
      }
      return { args: [], method: 'credentials' };
    }
    default:
      if (isInstagram && fs.existsSync(UPLOADED_COOKIES) && cookiesFileHasInstagram()) {
        return { args: ['--cookies', UPLOADED_COOKIES], method: 'upload-instagram' };
      }
      return { args: [], method: publicOnly ? 'public' : 'none' };
  }
}

export function getAuthStatus() {
  const config = loadAuthConfig();
  const { args, method } = getYtdlpAuthArgs();

  let fileInfo = null;
  if (method === 'upload' || method === 'session' || method === 'env') {
    const cookiesPath =
      method === 'env'
        ? process.env.YTDLP_COOKIES_FILE
        : fs.existsSync(UPLOADED_COOKIES)
          ? UPLOADED_COOKIES
          : null;
    if (cookiesPath && fs.existsSync(cookiesPath)) {
      fileInfo = { path: cookiesPath, ...analyzeCookiesFile(cookiesPath) };
    }
  }

  const hasInstagram =
    fileInfo?.hasInstagram ||
    Boolean(config.instagram?.sessionid?.trim());
  const hasFacebook =
    fileInfo?.hasFacebook ||
    Boolean(config.facebook?.c_user?.trim() && config.facebook?.xs?.trim());
  const hasAgeGateSite = fileInfo?.hasAgeGateSite || false;

  return {
    configured: args.length > 0,
    method,
    browser: config.browser,
    browserProfile: config.browserProfile || null,
    hasInstagram,
    hasFacebook,
    hasAgeGateSite,
    hasCredentials: Boolean(config.credentials?.username?.trim()),
    credentialsUsername: config.credentials?.username || '',
    instagram: {
      hasSessionid: Boolean(config.instagram?.sessionid?.trim()),
      hasDsUserId: Boolean(config.instagram?.ds_user_id?.trim()),
    },
    facebook: {
      hasCUser: Boolean(config.facebook?.c_user?.trim()),
      hasXs: Boolean(config.facebook?.xs?.trim()),
    },
    file: fileInfo,
    availableBrowsers: BROWSERS,
    methods: [
      {
        id: 'browser',
        label: 'Browser on this server',
        description: 'Read live cookies from Chrome/Firefox on the Ubuntu server (log in there once).',
      },
      {
        id: 'session',
        label: 'Paste session tokens',
        description: 'Copy cookie values from DevTools — no cookies.txt file needed.',
      },
      {
        id: 'credentials',
        label: 'Username & password',
        description: 'Login via yt-dlp (may fail with 2FA/captcha).',
      },
      {
        id: 'upload',
        label: 'Upload cookies.txt',
        description: 'Classic Netscape cookies file export.',
      },
      { id: 'none', label: 'None', description: 'Public content only.' },
    ],
  };
}

export function saveAuthSettings(body) {
  const current = loadAuthConfig();
  const method = body.method ?? current.method;

  if (!['none', 'browser', 'session', 'credentials', 'upload', 'env'].includes(method)) {
    throw new Error('Invalid auth method');
  }

  const next = {
    ...current,
    method: method === 'env' ? 'none' : method,
    browser: body.browser ?? current.browser,
    browserProfile: body.browserProfile ?? current.browserProfile,
    instagram: {
      sessionid: body.instagram?.sessionid ?? current.instagram?.sessionid ?? '',
      ds_user_id: body.instagram?.ds_user_id ?? current.instagram?.ds_user_id ?? '',
      csrftoken: body.instagram?.csrftoken ?? current.instagram?.csrftoken ?? '',
    },
    facebook: {
      c_user: body.facebook?.c_user ?? current.facebook?.c_user ?? '',
      xs: body.facebook?.xs ?? current.facebook?.xs ?? '',
    },
    credentials: { ...current.credentials },
  };

  if (body.credentials?.username !== undefined) {
    next.credentials.username = body.credentials.username.trim();
  }
  if (body.credentials?.password) {
    next.credentials.passwordEnc = encryptSecret(body.credentials.password);
  }

  if (method === 'session') {
    writeSessionCookies(next);
  }

  saveAuthConfig(next);
  return getAuthStatus();
}

export function validateCookiesContent(content) {
  if (!content || typeof content !== 'string') throw new Error('Empty cookies file');
  const trimmed = content.trim();
  if (trimmed.length < 20) throw new Error('Cookies file too small');
  const lines = trimmed.split('\n').filter((l) => l && !l.startsWith('#'));
  if (!lines.some((l) => l.split('\t').length >= 6)) {
    throw new Error('Invalid format — use Netscape cookies.txt');
  }
  return trimmed.endsWith('\n') ? trimmed : `${trimmed}\n`;
}

export function saveCookiesUpload(content) {
  ensureDataDir();
  const validated = validateCookiesContent(content);
  fs.writeFileSync(UPLOADED_COOKIES, validated, { mode: 0o600 });
  const config = loadAuthConfig();
  config.method = 'upload';
  saveAuthConfig(config);
  return getAuthStatus();
}

export function clearAuth() {
  if (fs.existsSync(UPLOADED_COOKIES)) fs.unlinkSync(UPLOADED_COOKIES);
  if (fs.existsSync(AUTH_CONFIG)) fs.unlinkSync(AUTH_CONFIG);
  return getAuthStatus();
}

export function getCookiesPath() {
  const { args } = getYtdlpAuthArgs();
  const idx = args.indexOf('--cookies');
  if (idx !== -1 && args[idx + 1]) return args[idx + 1];
  return null;
}

export function getCookiesStatus() {
  return getAuthStatus();
}

export function saveCookies(content) {
  return saveCookiesUpload(content);
}

export function deleteUploadedCookies() {
  if (fs.existsSync(UPLOADED_COOKIES)) fs.unlinkSync(UPLOADED_COOKIES);
  const config = loadAuthConfig();
  if (config.method === 'upload' || config.method === 'session') {
    config.method = 'none';
    saveAuthConfig(config);
  }
  return getAuthStatus();
}

export { UPLOADED_COOKIES };
