import {
  SiYoutube,
  SiYoutubemusic,
  SiInstagram,
  SiFacebook,
  SiTiktok,
  SiX,
  SiPinterest,
  SiReddit,
  SiTumblr,
  SiThreads,
  SiBluesky,
  SiSnapchat,
  SiVk,
  SiMastodon,
  SiVimeo,
  SiDailymotion,
  SiTwitch,
  SiKick,
  SiRumble,
  SiBilibili,
  SiNiconico,
  SiSoundcloud,
  SiBandcamp,
  SiMixcloud,
  SiSpotify,
  SiApplepodcasts,
  SiGoogle,
  SiTidal,
  SiAudiomack,
  SiImgur,
  SiCrunchyroll,
  SiNbc,
  SiCbs,
  SiTed,
  SiOdysee,
  SiPeertube,
  SiInternetarchive,
  SiLoom,
  SiWistia,
  SiDiscord,
  SiTelegram,
  SiWhatsapp,
  SiGoogledrive,
  SiDropbox,
  SiBox,
  SiMediafire,
  SiMega,
  SiGithub,
  SiGitlab,
  SiSourceforge,
  SiCoursera,
  SiUdemy,
  SiEdx,
  SiKhanacademy,
  SiNba,
  SiSteam,
  SiPlaystation,
  SiZoom,
  SiCnn,
  SiFox,
  SiLastdotfm,
  SiCbc,
  SiUfc,
  SiSony,
  SiNaver,
  SiKakao,
  SiBitbucket,
  SiOdnoklassniki,
  SiPixiv,
  SiSubstack,
  SiApple,
  SiCloudflare,
} from 'react-icons/si';
import { FaLinkedin, FaXbox, FaMicrosoft } from 'react-icons/fa6';
import { HiOutlineGlobeAlt, HiOutlineCloudArrowDown } from 'react-icons/hi2';
import { detectPlatformFromUrl as detectFromRegistry } from './platformDetect.js';

export const DEFAULT_BRAND = {
  Icon: HiOutlineGlobeAlt,
  color: '#64748b',
  bg: '#f1f5f9',
  key: null,
};

const PLATFORM_BRANDS = {
  youtube: { Icon: SiYoutube, color: '#FF0000', bg: '#fee2e2' },
  'youtube-music': { Icon: SiYoutubemusic, color: '#FF0000', bg: '#fee2e2' },
  'youtube-live': { Icon: SiYoutube, color: '#FF0000', bg: '#fee2e2' },
  instagram: { Icon: SiInstagram, color: '#E4405F', bg: '#fce7f3' },
  facebook: { Icon: SiFacebook, color: '#1877F2', bg: '#dbeafe' },
  tiktok: { Icon: SiTiktok, color: '#000000', bg: '#f1f5f9' },
  x: { Icon: SiX, color: '#000000', bg: '#f1f5f9' },
  pinterest: { Icon: SiPinterest, color: '#BD081C', bg: '#fee2e2' },
  reddit: { Icon: SiReddit, color: '#FF4500', bg: '#ffedd5' },
  linkedin: { Icon: FaLinkedin, color: '#0A66C2', bg: '#dbeafe' },
  tumblr: { Icon: SiTumblr, color: '#36465D', bg: '#e2e8f0' },
  threads: { Icon: SiThreads, color: '#000000', bg: '#f1f5f9' },
  bluesky: { Icon: SiBluesky, color: '#0085FF', bg: '#dbeafe' },
  snapchat: { Icon: SiSnapchat, color: '#FFFC00', bg: '#fef9c3' },
  vk: { Icon: SiVk, color: '#0077FF', bg: '#dbeafe' },
  mastodon: { Icon: SiMastodon, color: '#6364FF', bg: '#e0e7ff' },
  okru: { Icon: SiOdnoklassniki, color: '#EE8208', bg: '#ffedd5' },
  vimeo: { Icon: SiVimeo, color: '#1AB7EA', bg: '#e0f2fe' },
  dailymotion: { Icon: SiDailymotion, color: '#0066DC', bg: '#dbeafe' },
  twitch: { Icon: SiTwitch, color: '#9146FF', bg: '#ede9fe' },
  kick: { Icon: SiKick, color: '#53FC18', bg: '#dcfce7' },
  rumble: { Icon: SiRumble, color: '#85C742', bg: '#dcfce7' },
  bilibili: { Icon: SiBilibili, color: '#00A1D6', bg: '#e0f2fe' },
  niconico: { Icon: SiNiconico, color: '#231815', bg: '#f1f5f9' },
  soundcloud: { Icon: SiSoundcloud, color: '#FF5500', bg: '#ffedd5' },
  bandcamp: { Icon: SiBandcamp, color: '#629AA9', bg: '#e0f2fe' },
  mixcloud: { Icon: SiMixcloud, color: '#5000FE', bg: '#ede9fe' },
  spotify: { Icon: SiSpotify, color: '#1DB954', bg: '#dcfce7' },
  'apple-podcasts': { Icon: SiApplepodcasts, color: '#9933FF', bg: '#f3e8ff' },
  'google-podcasts': { Icon: SiGoogle, color: '#4285F4', bg: '#dbeafe' },
  tidal: { Icon: SiTidal, color: '#000000', bg: '#f1f5f9' },
  audiomack: { Icon: SiAudiomack, color: '#FFA200', bg: '#ffedd5' },
  imgur: { Icon: SiImgur, color: '#1BB76E', bg: '#dcfce7' },
  crunchyroll: { Icon: SiCrunchyroll, color: '#F47521', bg: '#ffedd5' },
  nbc: { Icon: SiNbc, color: '#6E6F71', bg: '#f1f5f9' },
  cbs: { Icon: SiCbs, color: '#419EF5', bg: '#dbeafe' },
  ted: { Icon: SiTed, color: '#E62B1E', bg: '#fee2e2' },
  odysee: { Icon: SiOdysee, color: '#EF1970', bg: '#fce7f3' },
  peertube: { Icon: SiPeertube, color: '#F1680B', bg: '#ffedd5' },
  loom: { Icon: SiLoom, color: '#625DF5', bg: '#e0e7ff' },
  wistia: { Icon: SiWistia, color: '#54BBFF', bg: '#e0f2fe' },
  discord: { Icon: SiDiscord, color: '#5865F2', bg: '#e0e7ff' },
  telegram: { Icon: SiTelegram, color: '#26A5E4', bg: '#e0f2fe' },
  whatsapp: { Icon: SiWhatsapp, color: '#25D366', bg: '#dcfce7' },
  archive: { Icon: SiInternetarchive, color: '#666666', bg: '#f1f5f9' },
  'google-drive': { Icon: SiGoogledrive, color: '#4285F4', bg: '#dbeafe' },
  dropbox: { Icon: SiDropbox, color: '#0061FF', bg: '#dbeafe' },
  onedrive: { Icon: FaMicrosoft, color: '#0078D4', bg: '#dbeafe' },
  box: { Icon: SiBox, color: '#0061D5', bg: '#dbeafe' },
  mediafire: { Icon: SiMediafire, color: '#1299F3', bg: '#e0f2fe' },
  mega: { Icon: SiMega, color: '#D9272E', bg: '#fee2e2' },
  github: { Icon: SiGithub, color: '#181717', bg: '#f1f5f9' },
  gitlab: { Icon: SiGitlab, color: '#FC6D26', bg: '#ffedd5' },
  sourceforge: { Icon: SiSourceforge, color: '#FF6600', bg: '#ffedd5' },
  coursera: { Icon: SiCoursera, color: '#0056D2', bg: '#dbeafe' },
  udemy: { Icon: SiUdemy, color: '#A435F0', bg: '#f3e8ff' },
  edx: { Icon: SiEdx, color: '#02262B', bg: '#e2e8f0' },
  'khan-academy': { Icon: SiKhanacademy, color: '#14BF96', bg: '#dcfce7' },
  nba: { Icon: SiNba, color: '#253B73', bg: '#dbeafe' },
  steam: { Icon: SiSteam, color: '#000000', bg: '#f1f5f9' },
  playstation: { Icon: SiPlaystation, color: '#0070D1', bg: '#dbeafe' },
  xbox: { Icon: FaXbox, color: '#107C10', bg: '#dcfce7' },
  zoom: { Icon: SiZoom, color: '#0B5CFF', bg: '#dbeafe' },
  cnn: { Icon: SiCnn, color: '#CC0000', bg: '#fee2e2' },
  fox: { Icon: SiFox, color: '#003366', bg: '#dbeafe' },
  'last-fm': { Icon: SiLastdotfm, color: '#D51007', bg: '#fee2e2' },
  cbc: { Icon: SiCbc, color: '#E60505', bg: '#fee2e2' },
  ufc: { Icon: SiUfc, color: '#D20A0A', bg: '#fee2e2' },
  sony: { Icon: SiSony, color: '#000000', bg: '#f1f5f9' },
  naver: { Icon: SiNaver, color: '#03C75A', bg: '#dcfce7' },
  kakao: { Icon: SiKakao, color: '#FFCD00', bg: '#fef9c3' },
  bitbucket: { Icon: SiBitbucket, color: '#0052CC', bg: '#dbeafe' },
  pixiv: { Icon: SiPixiv, color: '#0096FA', bg: '#e0f2fe' },
  substack: { Icon: SiSubstack, color: '#FF6719', bg: '#ffedd5' },
  apple: { Icon: SiApple, color: '#000000', bg: '#f1f5f9' },
  cloudflare: { Icon: SiCloudflare, color: '#F38020', bg: '#ffedd5' },
  'direct-http': { Icon: HiOutlineCloudArrowDown, color: '#2563eb', bg: '#dbeafe' },
};

const NAME_ALIASES = [
  [/youtube music/i, 'youtube-music'],
  [/youtube live/i, 'youtube-live'],
  [/youtube/i, 'youtube'],
  [/instagram live/i, 'instagram'],
  [/instagram/i, 'instagram'],
  [/facebook live/i, 'facebook'],
  [/facebook/i, 'facebook'],
  [/tiktok|douyin/i, 'tiktok'],
  [/^x\b|\(twitter\)|twitter/i, 'x'],
  [/pinterest/i, 'pinterest'],
  [/reddit/i, 'reddit'],
  [/linkedin learning|linkedin/i, 'linkedin'],
  [/tumblr/i, 'tumblr'],
  [/threads/i, 'threads'],
  [/bluesky/i, 'bluesky'],
  [/snapchat/i, 'snapchat'],
  [/\bvk\b|vkontakte|vk video/i, 'vk'],
  [/mastodon/i, 'mastodon'],
  [/vimeo/i, 'vimeo'],
  [/dailymotion/i, 'dailymotion'],
  [/twitch/i, 'twitch'],
  [/kick/i, 'kick'],
  [/rumble/i, 'rumble'],
  [/bilibili/i, 'bilibili'],
  [/niconico/i, 'niconico'],
  [/soundcloud/i, 'soundcloud'],
  [/bandcamp/i, 'bandcamp'],
  [/mixcloud/i, 'mixcloud'],
  [/spotify|anchor/i, 'spotify'],
  [/apple podcast/i, 'apple-podcasts'],
  [/google podcast/i, 'google-podcasts'],
  [/tidal/i, 'tidal'],
  [/audiomack/i, 'audiomack'],
  [/imgur/i, 'imgur'],
  [/crunchyroll/i, 'crunchyroll'],
  [/\bnbc\b/i, 'nbc'],
  [/\bcbs\b/i, 'cbs'],
  [/\bted\b/i, 'ted'],
  [/odysee|lbry/i, 'odysee'],
  [/peertube/i, 'peertube'],
  [/loom/i, 'loom'],
  [/wistia/i, 'wistia'],
  [/discord/i, 'discord'],
  [/telegram/i, 'telegram'],
  [/whatsapp/i, 'whatsapp'],
  [/archive\.org|internet archive/i, 'archive'],
  [/google drive/i, 'google-drive'],
  [/dropbox/i, 'dropbox'],
  [/onedrive/i, 'onedrive'],
  [/\bbox\b/i, 'box'],
  [/mediafire/i, 'mediafire'],
  [/mega\.nz|mega/i, 'mega'],
  [/github/i, 'github'],
  [/gitlab/i, 'gitlab'],
  [/sourceforge/i, 'sourceforge'],
  [/coursera/i, 'coursera'],
  [/udemy/i, 'udemy'],
  [/edx/i, 'edx'],
  [/khan academy/i, 'khan-academy'],
  [/\bnba\b/i, 'nba'],
  [/ufc/i, 'ufc'],
  [/steam/i, 'steam'],
  [/playstation/i, 'playstation'],
  [/xbox/i, 'xbox'],
  [/nintendo/i, 'nintendo'],
  [/zoom/i, 'zoom'],
  [/cnn/i, 'cnn'],
  [/\bfox\b/i, 'fox'],
  [/last\.fm/i, 'last-fm'],
  [/cbc/i, 'cbc'],
  [/sony/i, 'sony'],
  [/naver/i, 'naver'],
  [/kakao/i, 'kakao'],
  [/odnoklassniki|ok\.ru/i, 'okru'],
  [/bitbucket/i, 'bitbucket'],
  [/pixiv/i, 'pixiv'],
  [/substack/i, 'substack'],
  [/any http|direct http|direct link|http download|https url|ftp links/i, 'direct-http'],
];

export function resolvePlatformKey(nameOrUrl = '') {
  const text = String(nameOrUrl).trim();
  if (!text) return null;
  for (const [pattern, key] of NAME_ALIASES) {
    if (pattern.test(text)) return key;
  }
  return null;
}

export function detectPlatformFromUrl(url) {
  return detectFromRegistry(url);
}

// Legacy alias kept for getPlatformBrand
function detectPlatformFromUrlLegacy(url) {
  return detectFromRegistry(url);
}

export function getPlatformBrand(nameOrUrl) {
  const text = String(nameOrUrl || '').trim();
  const isUrl = /^(https?:)?\/\//i.test(text) || /^[\w-]+\.[\w.-]+\//.test(text);
  const key =
    resolvePlatformKey(text) ||
    (isUrl ? resolvePlatformKey(detectPlatformFromUrlLegacy(text)) : null) ||
    null;
  if (key && PLATFORM_BRANDS[key]) {
    return { ...PLATFORM_BRANDS[key], key };
  }
  return { ...DEFAULT_BRAND };
}

export const FEATURED_PLATFORMS = [
  'YouTube',
  'Instagram',
  'TikTok',
  'X (Twitter)',
  'Pinterest',
  'Facebook',
  'Vimeo',
  'Google Drive',
  'Dropbox',
  'Direct HTTP',
];
