/** Official site domains for favicon fallback (real site icons). */
export const PLATFORM_DOMAINS = {
  Instagram: 'instagram.com',
  Facebook: 'facebook.com',
  'Facebook Live': 'facebook.com',
  TikTok: 'tiktok.com',
  'X (Twitter)': 'x.com',
  Pinterest: 'pinterest.com',
  Reddit: 'reddit.com',
  LinkedIn: 'linkedin.com',
  'LinkedIn Learning': 'linkedin.com',
  Tumblr: 'tumblr.com',
  Threads: 'threads.net',
  Bluesky: 'bsky.app',
  Snapchat: 'snapchat.com',
  VK: 'vk.com',
  'VK Video': 'vk.com',
  'OK.ru': 'ok.ru',
  Weibo: 'weibo.com',
  Mastodon: 'joinmastodon.org',
  YouTube: 'youtube.com',
  'YouTube Music': 'music.youtube.com',
  'YouTube Live': 'youtube.com',
  'Instagram Live': 'instagram.com',
  Vimeo: 'vimeo.com',
  Dailymotion: 'dailymotion.com',
  Twitch: 'twitch.tv',
  Kick: 'kick.com',
  Rumble: 'rumble.com',
  Bilibili: 'bilibili.com',
  Niconico: 'nicovideo.jp',
  'Niconico Channel': 'nicovideo.jp',
  Rutube: 'rutube.ru',
  Youku: 'youku.com',
  IQiyi: 'iq.com',
  iQIYI: 'iq.com',
  NBC: 'nbc.com',
  CBS: 'cbs.com',
  ABC: 'abc.com',
  Fox: 'fox.com',
  'BBC iPlayer': 'bbc.co.uk',
  'BBC Sounds': 'bbc.co.uk',
  ITV: 'itv.com',
  'Channel 4': 'channel4.com',
  'Sky News': 'sky.com',
  'Al Jazeera': 'aljazeera.com',
  CNN: 'cnn.com',
  MSNBC: 'msnbc.com',
  'France TV': 'francetv.fr',
  'Arte TV': 'arte.tv',
  RTVE: 'rtve.es',
  ZDF: 'zdf.de',
  ARD: 'ard.de',
  NHK: 'nhk.or.jp',
  TED: 'ted.com',
  'C-SPAN': 'c-span.org',
  Crunchyroll: 'crunchyroll.com',
  Funimation: 'funimation.com',
  VRV: 'vrv.co',
  'Pluto TV': 'pluto.tv',
  'Odysee / LBRY': 'odysee.com',
  PeerTube: 'peertube.tv',
  BitChute: 'bitchute.com',
  Streamable: 'streamable.com',
  Loom: 'loom.com',
  Wistia: 'wistia.com',
  Vidyard: 'vidyard.com',
  SproutVideo: 'sproutvideo.com',
  Brightcove: 'brightcove.com',
  Kaltura: 'kaltura.com',
  Panopto: 'panopto.com',
  Mediasite: 'mediasite.com',
  LiveLeak: 'liveleak.com',
  Veoh: 'veoh.com',
  Metacafe: 'metacafe.com',
  Coub: 'coub.com',
  Imgur: 'imgur.com',
  Gfycat: 'gfycat.com',
  RedGifs: 'redgifs.com',
  SoundCloud: 'soundcloud.com',
  Bandcamp: 'bandcamp.com',
  Mixcloud: 'mixcloud.com',
  Audiomack: 'audiomack.com',
  Spotify: 'spotify.com',
  'Apple Podcasts': 'podcasts.apple.com',
  'Google Podcasts': 'podcasts.google.com',
  Anchor: 'anchor.fm',
  Simplecast: 'simplecast.com',
  Buzzsprout: 'buzzsprout.com',
  Libsyn: 'libsyn.com',
  Podbean: 'podbean.com',
  'Hype Machine': 'hypem.com',
  'Last.fm': 'last.fm',
  Deezer: 'deezer.com',
  Tidal: 'tidal.com',
  Audius: 'audius.co',
  'Radio France': 'radiofrance.fr',
  NPR: 'npr.org',
  CBC: 'cbc.ca',
  'RA (Resident Advisor)': 'ra.co',
  DLive: 'dlive.tv',
  Trovo: 'trovo.live',
  Caffeine: 'caffeine.tv',
  Restream: 'restream.io',
  'Zoom recordings': 'zoom.us',
  'Google Drive': 'drive.google.com',
  Dropbox: 'dropbox.com',
  OneDrive: 'onedrive.live.com',
  Box: 'box.com',
  MediaFire: 'mediafire.com',
  'Mega.nz': 'mega.nz',
  '4shared': '4shared.com',
  GoFile: 'gofile.io',
  Pixeldrain: 'pixeldrain.com',
  Catbox: 'catbox.moe',
  'Archive.org': 'archive.org',
  'Internet Archive TV': 'archive.org',
  'GitHub Releases': 'github.com',
  GitLab: 'gitlab.com',
  SourceForge: 'sourceforge.net',
  'Any HTTP/HTTPS URL': 'cloudflare.com',
  'Direct HTTP': 'cloudflare.com',
  'Khan Academy': 'khanacademy.org',
  Coursera: 'coursera.org',
  Udemy: 'udemy.com',
  Skillshare: 'skillshare.com',
  Pluralsight: 'pluralsight.com',
  edX: 'edx.org',
  'MIT OpenCourseWare': 'mit.edu',
  'Stanford Online': 'stanford.edu',
  Canvas: 'instructure.com',
  'Canvas LMS': 'instructure.com',
  Blackboard: 'blackboard.com',
  Moodle: 'moodle.org',
  ESPN: 'espn.com',
  NBA: 'nba.com',
  NFL: 'nfl.com',
  MLB: 'mlb.com',
  UFC: 'ufc.com',
  'Formula 1': 'formula1.com',
  Olympics: 'olympics.com',
  DAZN: 'dazn.com',
  Hotstar: 'hotstar.com',
  JioCinema: 'jiocinema.com',
  SonyLIV: 'sonyliv.com',
  Zee5: 'zee5.com',
  AbemaTV: 'abema.tv',
  TVer: 'tver.jp',
  AfreecaTV: 'afreecatv.com',
  'Naver TV': 'tv.naver.com',
  KakaoTV: 'tv.kakao.com',
  Douyin: 'douyin.com',
  'Tencent Video': 'v.qq.com',
  Newgrounds: 'newgrounds.com',
  GameSpot: 'gamespot.com',
  IGN: 'ign.com',
  Steam: 'store.steampowered.com',
  PlayStation: 'playstation.com',
  Xbox: 'xbox.com',
  Nintendo: 'nintendo.com',
  OpenRec: 'openrec.tv',
  Pornhub: 'pornhub.com',
  XVideos: 'xvideos.com',
  XHamster: 'xhamster.com',
  'Full list': 'ytdlp.org',
};

const DOMAIN_ALIASES = [
  [/instagram/i, 'instagram.com'],
  [/facebook|fb\.watch/i, 'facebook.com'],
  [/tiktok/i, 'tiktok.com'],
  [/twitter|x\.com/i, 'x.com'],
  [/pinterest/i, 'pinterest.com'],
  [/reddit|redd\.it/i, 'reddit.com'],
  [/linkedin/i, 'linkedin.com'],
  [/youtube|youtu\.be/i, 'youtube.com'],
  [/vimeo/i, 'vimeo.com'],
  [/twitch/i, 'twitch.tv'],
  [/soundcloud/i, 'soundcloud.com'],
  [/spotify/i, 'spotify.com'],
  [/drive\.google/i, 'drive.google.com'],
  [/dropbox/i, 'dropbox.com'],
  [/github/i, 'github.com'],
  [/gitlab/i, 'gitlab.com'],
  [/archive\.org/i, 'archive.org'],
  [/mega\.nz/i, 'mega.nz'],
  [/mediafire/i, 'mediafire.com'],
  [/bilibili/i, 'bilibili.com'],
  [/dailymotion/i, 'dailymotion.com'],
  [/kick\.com/i, 'kick.com'],
  [/rumble/i, 'rumble.com'],
  [/ted\.com/i, 'ted.com'],
  [/cnn\.com/i, 'cnn.com'],
  [/nbc/i, 'nbc.com'],
  [/cbs/i, 'cbs.com'],
  [/bbc/i, 'bbc.co.uk'],
  [/npr/i, 'npr.org'],
  [/crunchyroll/i, 'crunchyroll.com'],
  [/odysee|lbry/i, 'odysee.com'],
  [/pornhub/i, 'pornhub.com'],
  [/xvideos/i, 'xvideos.com'],
  [/xhamster/i, 'xhamster.com'],
  [/redtube/i, 'redtube.com'],
  [/youporn/i, 'youporn.com'],
  [/spankbang/i, 'spankbang.com'],
  [/xnxx/i, 'xnxx.com'],
  [/streamable/i, 'streamable.com'],
  [/bandcamp/i, 'bandcamp.com'],
  [/mixcloud/i, 'mixcloud.com'],
  [/newgrounds/i, 'newgrounds.com'],
  [/peertube/i, 'peertube.tv'],
  [/imgur/i, 'imgur.com'],
  [/bandcamp/i, 'bandcamp.com'],
  [/mixcloud/i, 'mixcloud.com'],
  [/deezer/i, 'deezer.com'],
  [/tidal/i, 'tidal.com'],
  [/zoom\.us/i, 'zoom.us'],
  [/coursera/i, 'coursera.org'],
  [/udemy/i, 'udemy.com'],
  [/edx/i, 'edx.org'],
  [/steam/i, 'store.steampowered.com'],
  [/playstation/i, 'playstation.com'],
  [/xbox/i, 'xbox.com'],
  [/nintendo/i, 'nintendo.com'],
  [/hotstar/i, 'hotstar.com'],
  [/douyin/i, 'douyin.com'],
  [/weibo/i, 'weibo.com'],
  [/nicovideo|niconico/i, 'nicovideo.jp'],
  [/rutube/i, 'rutube.ru'],
  [/youku/i, 'youku.com'],
  [/iqiyi|iq\.com/i, 'iq.com'],
  [/vk\.com/i, 'vk.com'],
  [/ok\.ru/i, 'ok.ru'],
  [/threads\.net/i, 'threads.net'],
  [/bsky\.app/i, 'bsky.app'],
  [/mastodon/i, 'joinmastodon.org'],
  [/snapchat/i, 'snapchat.com'],
  [/tumblr/i, 'tumblr.com'],
  [/loom\.com/i, 'loom.com'],
  [/wistia/i, 'wistia.com'],
  [/streamable/i, 'streamable.com'],
  [/bitchute/i, 'bitchute.com'],
  [/pluto\.tv/i, 'pluto.tv'],
  [/gofile/i, 'gofile.io'],
  [/pixeldrain/i, 'pixeldrain.com'],
  [/http|https|direct/i, 'cloudflare.com'],
];

export function getPlatformDomain(nameOrUrl = '') {
  const text = String(nameOrUrl).trim();
  if (!text) return null;

  if (PLATFORM_DOMAINS[text]) return PLATFORM_DOMAINS[text];

  const lower = text.toLowerCase();
  for (const [name, domain] of Object.entries(PLATFORM_DOMAINS)) {
    if (name.toLowerCase() === lower) return domain;
  }

  for (const [pattern, domain] of DOMAIN_ALIASES) {
    if (pattern.test(text)) return domain;
  }

  try {
    const host = new URL(text).hostname.replace(/^www\./, '');
    if (host) return host;
  } catch {
    /* not a URL */
  }

  return null;
}

export function faviconUrl(domain, size = 128) {
  if (!domain) return null;
  return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=${size}`;
}
